kind: pipeline
type: docker
name: systemIntegrationBot

trigger:
  branch:
  - deploy
  - main

steps:
- name: systemIntegrationBot image publish 
  image: plugins/docker
  settings:
    username: root
    password: pa55word
    insecure: true
    repo: 192.168.1.111:5000/tvi/systemintegrationbot
    registry: 192.168.1.111:5000
    dockerfile: Dockerfile
    tags: latest

- name: systemIntegrationBotDiscord image publish 
  image: plugins/docker
  settings:
    username: root
    password: pa55word
    insecure: true
    repo: 192.168.1.111:5000/tvi/systemintegrationbotdiscord
    registry: 192.168.1.111:5000
    dockerfile: sid/Dockerfile
    tags: latest

- name: systemIntegrationBot ssh commands
  image: appleboy/drone-ssh:1.6.0
  settings:
    host: 192.168.1.121
    username: root
    password: 
      from_secret: ssh_password_121
    port: 24308
    script:
    - docker stop sstmintgrtnbot
    - docker rm sstmintgrtnbot
    - docker pull 192.168.1.111:5000/tvi/systemintegrationbot
    - docker run -t -i --name sstmintgrtnbot --restart=always -d --env-file /systemintegrationbot/.env 192.168.1.111:5000/tvi/systemintegrationbot:latest
    - if [[ $(docker image ls -f dangling=true -q) != '' ]]; then docker image rm $(docker image ls -f dangling=true -q); fi
    - docker image tag 192.168.1.111:5000/tvi/systemintegrationbot:latest systemintegrationbot
    - docker save systemintegrationbot > /systemintegrationbot/systemintegrationbot.tar
  depends_on:
  - systemIntegrationBot image publish

- name: systemIntegrationBotDiscord ssh commands
  image: appleboy/drone-ssh:1.6.0
  settings:
    host: 192.168.1.121
    username: root
    password: 
      from_secret: ssh_password_121
    port: 24308
    script:
    - docker stop sstmintgrtnbotdiscord
    - docker rm sstmintgrtnbotdiscord
    - docker pull 192.168.1.111:5000/tvi/systemintegrationbotdiscord
    - docker run -t -i --name sstmintgrtnbotdiscord --restart=always -d --env-file /systemintegrationbot/sid/.env 192.168.1.111:5000/tvi/systemintegrationbotdiscord:latest
    - if [[ $(docker image ls -f dangling=true -q) != '' ]]; then docker image rm $(docker image ls -f dangling=true -q); fi
    - docker image tag 192.168.1.111:5000/tvi/systemintegrationbotdiscord:latest systemintegrationbotdiscord
    - docker save systemintegrationbotdiscord > /systemintegrationbot/systemintegrationbotdiscord.tar
  depends_on:
  - systemIntegrationBotDiscord image publish

- name: systemIntegrationBot send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: TBOTTOKEN
    to: 
      from_secret: user_id
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
  depends_on:
  - systemIntegrationBot ssh commands